services:
  mongodb:
    image: mongo 
    ports: 
        - 27017:27017
    environment:
        MONGO_INITDB_USERNAME: admin
        MONGO_INITDB_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:          

